version: '3.0'
services:

  hoteles-db:
    image: mysql:8.0.30
    ports:
      - "3308:3306"
    environment:
      - "MYSQL_DATABASE=hotelesdb"
      - "MYSQL_ROOT_PASSWORD=root"
      - "DEFAULT_ENCODING=UTF8"

  vuelos-db:
    image: mongo:6.0
    container_name: "vuelos-db"
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=root"
      - "MONGO_INITDB_DATABASE=vuelosdb"
    volumes:
      - database:/data/db

  reservas-db:
    image: mysql:8.0.30
    ports:
      - "3307:3306"
    environment:
      - "MYSQL_DATABASE=reservasdb"
      - "MYSQL_ROOT_PASSWORD=root"
      - "DEFAULT_ENCODING=UTF8"

  servicio-eureka-server:
    build: ./springboot-servicio-eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - servicio-config-server
    environment:
      - "EUREKA_HOST=servicio-eureka-server"
      - "GATEWAY_HOST=servicio-gateway-server"
    restart: always

  servicio-config-server:
    build: ./springboot-servicio-config-server
    ports:
      - "8888:8888"
    environment:
      - "EUREKA_HOST=servicio-eureka-server"
      - "GATEWAY_HOST=servicio-gateway-server"
    restart: always

  servicio-gateway-server:
    build: ./springboot-servicio-gateway-server
    ports:
      - "8090:8090"
    depends_on:
      - servicio-config-server
      - servicio-eureka-server
    environment:
      - "EUREKA_HOST=servicio-eureka-server"
      - "CONFIG_HOST=servicio-config-server"
      - "ZIPKIN_HOST=zipkin"
      - "RABBITMQ_HOST=rabbitmq"
    restart: always

  rabbitmq:
    image: rabbitmq:3.7.6-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"
    networks:
      - local

  zipkin:
    image: openzipkin/zipkin:2.10.2
    container_name: zipkin
    depends_on:
      - rabbitmq
    ports:
      - "9411:9411"
    environment:
      - "TZ=@timezone@"
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"
    networks:
      - local
    restart: always

networks:
  local:

volumes:
  database: