version: '3.7'
services:
  reservas:
    build: ./reservas
    ports:
      - "8080:8080"
    depends_on:
      - reservas-db
    environment:
      - "reservas-port=3306"
      - "reservas-db=reservas-db"
      - "hoteles-host=hoteles"
      - "vuelos-host=vuelos"
    restart: always
  reservas-db:
    image: mysql:8.0.30
    ports:
      - "3307:3306"
    environment:
      - "MYSQL_DATABASE=reservasdb"
      - "MYSQL_ROOT_PASSWORD=root"
      - "DEFAULT_ENCODING=UTF8"

  hoteles:
    build: ./hoteles
    ports:
      - "8081:8081"
    depends_on:
      - hoteles-db
    environment:
      - "hoteles-port=3306"
      - "hoteles-db=hoteles-db"
      - "reservas-host=reservas"
    restart: always

  hotelesofer:
    build: ./hotelesofer
    ports:
      - "8081:8081"
    depends_on:
      - hoteles-db
    environment:
      - "hoteles-port=3306"
      - "hoteles-db=hoteles-db"
      - "reservas-host=reservas"
    restart: always

  hoteles-db:
    image: mysql:8.0.30
    ports:
      - "3308:3306"
    environment:
      - "MYSQL_DATABASE=hotelesdb"
      - "MYSQL_ROOT_PASSWORD=root"
      - "DEFAULT_ENCODING=UTF8"
  vuelos:
    build: ./vuelos
    ports:
      - "8082:8082"
    depends_on:
      - vuelos-db
    environment:
      - "vuelos-db=vuelos-db"
      - "reservas-host=reservas"
      - "vuelos-port=5432"
    restart: always

  vuelosofer:
    build: ./vuelosofer
    ports:
      - "8082:8082"
    depends_on:
      - vuelos-db
    environment:
      - "vuelos-db=vuelos-db"
      - "reservas-host=reservas"
      - "vuelos-port=5432"
    restart: always

  vuelos-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=benedi"
      - "POSTGRES_PASSWORD=benedi"
      - "DEFAULT_ENCODING=UTF8"
      - "POSTGRES_DB=vuelosdb"

  rabbitmq:
    image: rabbitmq:3.7.6-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"
    networks:
      - local

  zipkin:
    image: openzipkin/zipkin:2.10.2
    container_name: zipkin
    depends_on:
      - rabbitmq
    ports:
      - "9411:9411"
    environment:
      - "TZ=@timezone@"
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"
    networks:
      - local
    restart: always

networks:
  local: