spring:
  config:
    activate:
      on-profile: default
  application:
    name: hoteles
  cloud:
    config:
      uri: http://${CONFIG_SERVER:localhost}:8888

app:
  environment:
    reservas-host: ${reservas-host:localhost}

--- # Testing config

server:
  port: ${random.int(5000,5100)}

spring:
  config:
    activate:
      on-profile: test
  application:
    name: hoteles
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: tomas
    password: tomas
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true