spring:
  config:
    activate:
      on-profile: default
  application:
    name: hoteles
  cloud:
    config:
      uri: http://${CONFIG_SERVER:localhost}:8888

app:
  environment:
    reservas-host: ${reservas-host:localhost}