spring:
  cloud:
    gateway:
      routes:
      - id: hotelesofer
        uri: lb://hotelesofer
        predicates:
          - Path=/hotelOfertas/**
        #filters:
        #  - StripPrefix=2
      - id: vuelossofer
        uri: lb://vuelosofer
        predicates:
          - Path=/vueloOfertas/**
      - id: reservas
        uri: lb://reservas
        predicates:
          - Path=/reservas/**
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
          - Path=/api-items/**
        filters:
          - StripPrefix=1